server:
  port: 8083

spring:
  application:
    name: event-microservice # Nom de l'application pour identification dans Eureka
  datasource:
    url: jdbc:mysql://localhost:3306/event
    username: root
    password: azerty12346
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8888 # Adresse de votre Config Server
      import: "optional:configserver:" # Utilisation correcte de configserver avec optional pour éviter l'erreur
      import-check:
        enabled: false # Désactiver la vérification de l'importation de configuration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
